---
en:
  - Index: index.md
  - Changes: changes.md
  - Getting Started: getting_started.md
  - setup:
      - install-straight:
          - Basic: setup/install-straight/basic.md
          - Advanced: setup/install-straight/advanced.md
      - Install Straight Server: setup/install_straight-server.md
  - configuring:
      - Overview: configuring/overview.md
      - Tips and Tricks: configuring/tips_and_tricks.md